In [1]:
import numpy as np

In [10]:
arr1 = np.array([1,2,3,4,5]) #[] #[[[],[]]]

In [6]:
arr1.shape

(1, 5)

In [8]:
arr1.dtype

dtype('int32')

In [11]:
arr1.ndim

1

In [12]:
arr1 = np.array([1,2,3,4,5], dtype=np.float)

C:\Users\rips\AppData\Local\Temp/ipykernel_3532/1337087596.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr1 = np.array([1,2,3,4,5], dtype=np.float)


In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr3 = np.arange(0,10,1.5)
arr3

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [16]:
arr_random = np.random.random((10,))

In [17]:
arr_random

array([0.33043044, 0.59686344, 0.63833597, 0.46684935, 0.2437274 ,
       0.26154545, 0.72145362, 0.22481248, 0.90509152, 0.99575786])

In [18]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr2_sqrt = np.sqrt(arr2)

In [20]:
arr2_sqrt


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [23]:
arr1 = np.arange(10,20)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
arr1 + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [24]:
arr1*arr2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [25]:
arr1**2

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [26]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
arr1.max()

19

In [28]:
arr1.mean()

14.5

In [29]:
arr1.sum()

145

In [30]:
arr1.std()

2.8722813232690143

In [31]:
arr1 > 14

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
# create array 1-dim through arange method and check ndim, shape, find the root of std

In [32]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
np.insert(arr1, 5, 10)

array([10, 11, 12, 13, 14, 10, 15, 16, 17, 18, 19])

In [34]:
np.delete(arr1, 5)

array([10, 11, 12, 13, 14, 16, 17, 18, 19])

In [35]:
arr4 = np.array([1,10,5,33,3])
np.sort(arr4)

array([ 1,  3,  5, 10, 33])

In [36]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr = np.concatenate((arr1, arr2))
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [39]:
arr[(arr < 5)]  

array([0, 1, 2, 3, 4])

In [40]:
arr[(arr < 10) & (arr > 5)]

array([6, 7, 8, 9])

In [41]:
arr[(arr < 3) | (arr > 17)] # and == & , or == | 

array([18, 19,  0,  1,  2])

In [42]:
arr[(arr < 3) & (arr > 17)]

array([], dtype=int32)

In [44]:
matrix1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
matrix1.shape

(3, 3)

In [46]:
matrix1.ndim

2

In [47]:
matrix1.size

9

In [53]:
matrix1.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [59]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
np.empty(2)

array([-3.86271701e+180,  1.08277788e-061])

In [61]:
a = np.empty_like(arr2)

In [62]:
a

array([790431024,       486,         0,         0,   6357101,   7471220,
         7864425,        46,         0,         0])

In [63]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
matrix2 = np.array([(10,11,12),(13,14,15),(16,17,18)])

In [67]:
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [68]:
matrix1 + matrix2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [69]:
np.delete(matrix1, 2, axis=0) #axis = 0 - row, axis = 1 - column

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
np.mean(matrix1, axis=0)

array([4., 5., 6.])

In [ ]:
[][][] - rows 0
[][][]
[][][]
cols - 1

In [76]:
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [77]:
matrix2[1,2] #0,1

15

In [78]:
matrix2[:,1] # [rows, columns]

array([11, 14, 17])

In [79]:
matrix2[matrix2 > 10] #table[table > 100]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:
# create 2 matrices with size 12 and 12, 
#add values
#through slicing get an optional row, column
#get values which are bigger than 5