In [1]:
import numpy as np

In [9]:
arr1 = np.array([1,2,3,4,5])

In [10]:
arr1.shape

(5,)

In [8]:
arr1.dtype

dtype('int32')

In [11]:
arr1.ndim

1

In [12]:
arr1 = np.array([1,2,3,4,5], dtype=np.float)

C:\Users\rips\AppData\Local\Temp/ipykernel_3532/1337087596.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr1 = np.array([1,2,3,4,5], dtype=np.float)


In [13]:
arr1.dtype

dtype('float64')

In [ ]:
#range(10,20,2)

In [14]:
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr3 = np.arange(0,10,1.5)
arr3

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [15]:
arr_random = np.random.random((10,))

In [16]:
arr_random

array([0.6711011 , 0.28157486, 0.29001937, 0.49807257, 0.15336255,
       0.66261616, 0.0428232 , 0.68079307, 0.18880065, 0.46571468])

In [17]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# a = [1,2,3,4,5]
# b = [i**2 for i in a]

In [18]:
arr2_sqrt = np.sqrt(arr2)

In [19]:
arr2_sqrt


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [20]:
np.sin(arr2)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [21]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#l1 + l2 => [l1, l2]

In [23]:
arr1 = np.arange(10,20)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
arr1 + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [24]:
arr1*arr2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [25]:
arr1**2

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [26]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
arr1.max()

19

In [28]:
arr1.mean()

14.5

In [29]:
arr1.sum()

145

In [30]:
arr1.std()

2.8722813232690143

In [31]:
arr1 > 14

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
# create array 1-dim through arange method and check ndim, shape, find the root of std

In [26]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.insert(arr2, 5, 10)

array([ 0,  1,  2,  3,  4, 10,  5,  6,  7,  8,  9])

In [28]:
np.delete(arr2, 5)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [29]:
arr4 = np.array([1,10,5,33,3])
np.sort(arr4)

array([ 1,  3,  5, 10, 33])

In [36]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr = np.concatenate((arr1, arr2))  #l1+l2 = [l1,l2] ar1+ar2=ar1i+ar2i, ....
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [39]:
arr[(arr < 5)]

array([0, 1, 2, 3, 4])

In [ ]:
#AND - & ; OR - | 

In [32]:
arr2[(arr2<10) & (arr2>5)]

array([6, 7, 8, 9])

In [34]:
arr2[(arr2<6) | (arr2>7)]

array([0, 1, 2, 3, 4, 5, 8, 9])

In [41]:
arr[(arr < 3) | (arr > 17)] # and == & , or == | 

array([18, 19,  0,  1,  2])

In [42]:
arr[(arr < 3) & (arr > 17)]

array([], dtype=int32)

In [44]:
matrix1 = np.array([(1,2,3),(4,5,6),(7,8,9)])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
matrix = np.array([(11, 12, 13), (1, 2, 3), (21, 22, 23)])

In [36]:
matrix

array([[11, 12, 13],
       [ 1,  2,  3],
       [21, 22, 23]])

In [37]:
matrix.shape

(3, 3)

In [39]:
matrix.ndim

2

In [40]:
matrix.size

9

In [53]:
matrix1.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [43]:
np.empty((3,3))

array([[0.84147098, 0.90929743, 0.14112001],
       [0.7568025 , 0.95892427, 0.2794155 ],
       [0.6569866 , 0.98935825, 0.41211849]])

In [46]:
np.empty(2)

array([7.97009677e+291, 1.97192262e-224])

In [48]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a = np.empty_like(arr2)

In [50]:
a

array([         0, 1072693248,          0, 1072693248,          0,
       1072693248,          0, 1072693248,          0, 1072693248])

In [63]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
matrix2 = np.array([(10,11,12),(13,14,15),(16,17,18)])

In [67]:
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [68]:
matrix1 + matrix2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [ ]:
# np.dot(m1, m2) 

In [51]:
matrix

array([[11, 12, 13],
       [ 1,  2,  3],
       [21, 22, 23]])

In [52]:
np.delete(matrix, 2, axis=0) #axis = 0 - row, axis = 1 - column

array([[11, 12, 13],
       [ 1,  2,  3]])

In [53]:
np.delete(matrix, 2, axis=1)

array([[11, 12],
       [ 1,  2],
       [21, 22]])

In [71]:
np.mean(matrix1, axis=0)

array([4., 5., 6.])

In [ ]:
[][][] - rows 0
[][][]
[][][]
cols - 1

In [76]:
matrix2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [55]:
matrix

array([[11, 12, 13],
       [ 1,  2,  3],
       [21, 22, 23]])

In [54]:
matrix[1,2] #0,1

3

In [56]:
matrix[:,1] # [rows, columns]

array([12,  2, 22])

In [58]:
matrix < 5

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [59]:
matrix[matrix < 5] #table[table > 100]

array([1, 2, 3])

In [ ]:
# create 2 matrices with size 12 and 12, 
#add values
#through slicing get an optional row, column
#get values which are bigger than 5